# Generated by Django 3.1.7 on 2021-03-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20200110_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='start_exam_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
